### ISSUE TITLE
Autoselection for connector type

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/opunit#19]
Support the ability to know whether using vagrant, Baker, docker, or ssh connector based on parameters provided and content of current working directory (Vagrantfile/baker.yml).

**Comment by ssmirr** [comment]
### Current way of using Opunit:

``` shell
$ opunit verify [env_address] [--ssh_key | --vagrant | --connector] 
```
one or more of these "parameters" are required depending on what connector you use (except for [Baker](/ottomatica/Baker) connector). **what we want to achieve** is to be able to run `opunit verify` or `opunit verify [env_address]` for most cases.

--- 

### Proposing this solution:
Opunit should check if it can use a connector in this order:
1. If there is `./Baker.yml` file in cwd, use Baker connector (`already implemented`)
2. If there is `./Vagrantfile` file in cwd, use Vagrant connector.
3. If `argv.env_address` can be matched to `{user}@{host}:{port}`, use ssh connector
4. If `argv.env_address` is an existing Docker container, use Docker connector
5. If `argv.env_address` is an existing Vagrant vm, use Vagrant connector
