### ISSUE TITLE
permission check should be supported when using local connector

### ISSUE THREAD

**Issue by ssmirr** [ottomatica/opunit#277]
**Describe the bug**
Permissions check is only implemented for ssh connectors:
```
✔   [/tmp/foo] status: true actual permission: permission is currently not supported in this connector
```

**To Reproduce**
Run the tests and check the report for local connector:
```
npm test
```

**Expected behavior**
```
✔   [/tmp/foo] status: true expected permission: 666 actual permission: 666 root root
```

**Please complete the following information:**
 - OS: Windows, MacOS, Linux
 - Version: #dev

**Comment by chrisparnin** [comment]
Samim has a work in progress in #dev. 

Need to complete work in `octal2rwx`. Basically need a function to convert `664` to `-rw-rw-r--`.

**Comment by ssmirr** [comment]
We can use `fs.stat()` function to get file permissions:

```js
let stats = await fs.promises.stat('path/to/file');
```
which returns:
```js
Stats {
  dev: 65024,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 25832094,
  size: 2666,
  blocks: 8,
  atimeMs: 1593802120098.7378,
  mtimeMs: 1594259581231.7642,
  ctimeMs: 1594259581231.7642,
  birthtimeMs: 1593802120098.7378,
  atime: 2020-07-03T18:48:40.099Z,
  mtime: 2020-07-09T01:53:01.232Z,
  ctime: 2020-07-09T01:53:01.232Z,
  birthtime: 2020-07-03T18:48:40.099Z
}
```

`mode` property can be converted to octal permission:
```js
console.log((stats.mode & parseInt("777", 8)).toString(8))
// 644
```

**Comment by ssmirr** [comment]
Nodejs fs flags _might_ also be useful for checking local file permissions: https://nodejs.org/api/fs.html#fs_file_system_flags
