### ISSUE TITLE
update README.md to install node.js npm module directly from GitHub repo

### ISSUE THREAD

**Issue by evandrix** [ottomatica/opunit#8]
## Install from source

> ~~git clone https://github.com/ottomatica/opunit
> cd opunit
> npm install
> npm link~~

`sudo npm i -g --unsafe-perm=true git+https://git@github.com/ottomatica/opunit.git`

**Comment by chrisparnin** [comment]
Great idea! We just published this module to npm so that we can now install with `npm install -g opunit`, however, we'll leave this instructions up for people that might want to hack with the source.
